//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitKit1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LitKit1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Group {
            get {
                object obj = ResourceManager.GetObject("Group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_delete_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-delete-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_erase_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-erase-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_pencil_drawing_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-pencil-drawing-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_plus_math_60 {
            get {
                object obj = ResourceManager.GetObject("icons8-plus-math-60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_refresh_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-refresh-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;license id=&quot;27ee3c0e-def1-4a1b-b828-315782be33ba&quot; expiration=&quot;2020-09-02T19:24:01.9710635&quot; type=&quot;Trial&quot;&gt;
        ///  &lt;name&gt;Test License&lt;/name&gt;
        ///  &lt;Signature xmlns=&quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;
        ///    &lt;SignedInfo&gt;
        ///      &lt;CanonicalizationMethod Algorithm=&quot;http://www.w3.org/TR/2001/REC-xml-c14n-20010315&quot; /&gt;
        ///      &lt;SignatureMethod Algorithm=&quot;http://www.w3.org/2001/04/xmldsig-more#rsa-sha256&quot; /&gt;
        ///      &lt;Reference URI=&quot;&quot;&gt;
        ///        &lt;Transforms&gt;
        ///          &lt;Transform Algorith [rest of string was truncated]&quot;;.
        /// </summary>
        public static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;v17shViD7bFwTSpNjJcxEdQ2JGncp8F8TjBp7+2uZzzBRLDV2du2s2LTbTEHAJW5yr0UhWj4MhAsjsAMD3Vi9QhTV4vhgVIZchfiGeEL9M0lMLm2uWAio9hAWV2yM10JS5mqFZfiX4EM1ltAsBpqXOrk04mvQCmf7J8Z81l1UAU=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;/RSAKeyValue&gt;.
        /// </summary>
        public static string publicKey {
            get {
                return ResourceManager.GetString("publicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Responses xmlns=&quot;Prelimine Litkit Response Tool&quot;&gt;
        ///  &lt;Document&gt;
        ///    &lt;Responding&gt;[Enter the Responding Party or Parties]&lt;/Responding&gt;
        ///    &lt;RespondingPlural&gt;False&lt;/RespondingPlural&gt;
        ///    &lt;Propounding&gt;[Enter the Propounding Party or Parties]&lt;/Propounding&gt;
        ///    &lt;DocType&gt;Answer a Complaint&lt;/DocType&gt;
        ///  &lt;/Document&gt;
        ///  &lt;Response xmlns=&quot;&quot;&gt;
        ///    &lt;ID&gt;1&lt;/ID&gt;
        ///    &lt;Name&gt;Objection: Cumulative&lt;/Name&gt;
        ///    &lt;DocType&gt;
        ///      &lt;Complaint&gt;False&lt;/Complaint&gt;
        ///      &lt;Adm [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ResponseFrame {
            get {
                return ResourceManager.GetString("ResponseFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Responses xmlns=&quot;Prelimine Litkit Response Tool Standard Language&quot;&gt;
        ///  &lt;Response xmlns=&quot;&quot;&gt;
        ///		&lt;ID&gt;1&lt;/ID&gt;
        ///		&lt;Name&gt;Objection: Cumulative&lt;/Name&gt;
        ///		&lt;DocType&gt;
        ///			&lt;Complaint&gt;False&lt;/Complaint&gt;
        ///			&lt;Admission&gt;True&lt;/Admission&gt;
        ///			&lt;Production&gt;True&lt;/Production&gt;
        ///			&lt;Interrogatory&gt;True&lt;/Interrogatory&gt;
        ///		&lt;/DocType&gt;
        ///		&lt;Text&gt;
        ///			&lt;Primary&gt;[Responding] [verb1] to this [Request/Interrogatory] as cumulative of prior discovery requests.&lt;/Primary&gt;
        ///			&lt;Alt1&gt;[Respo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ResponseStandardLanguage {
            get {
                return ResourceManager.GetString("ResponseStandardLanguage", resourceCulture);
            }
        }
    }
}
